### PR TITLE
Update to Target Cake 1.0.0

### LINKED ISSUE #30: Update Cake.Xamarin to target Cake v1.0.0
## Expected Behavior

Cake.Xamarin should be compatible with the current version of Cake.

## Current Behavior

Cake.Xamarin is not compatible with the current version of Cake.

## Possible Solution

Update Cake references to target Cake 1.0.0

## Steps to Reproduce (for bugs)
Errors out when using with Cake.Tool >= 1.0.0

### PR DESCRIPTION
**Pull request by dmariogatto**
## Description
Update Cake dependencies.

## Related Issue
#30

## Motivation and Context
Support for Cake 1.0.0

## How Has This Been Tested?

Existing `AndroidTests`/`iOSTests` are passing. No new tests added.

I was unable to get `TestCloudTests` and `XamarinComponentTests` to pass. However, I couldn't get them to run on the current main branch either... I'm not sure if these tests are still relevant.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed. (Kind of... technically they were all commented out 😅)

### CODE REVIEW

**Comment by dmariogatto** [comment]
@augustoproiete Any movement on this PR? Do you need anything from me?

**Comment by augustoproiete** [comment]
> Any movement on this PR? Do you need anything from me?

Thanks for the nudge @dmariogatto will get this one merged in a few

**Review by augustoproiete — APPROVED** [review]
LGTM!

**Comment by augustoproiete** [comment]
@dmariogatto your changes have been merged, thanks for your contribution :+1: and sorry for the huge delay in getting this one merged.

Will release a new version to nuget.org asap

**Pull request merged**
